### ISSUE TITLE
Design and implement the game lobby page.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Client#12]

**Comment by Dzl666** [comment]
@dominic1712  https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/0c9493ad5787ab2e77df760ad9703a9116dcc6dd, @Dzl666 https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/02135446b433f8623074c520cadb81ae688c4f23

**Comment by dominic1712** [comment]
new assigned user story: [As a user want to start a game, I want to select the area of cities that will appear in the game, so I can narrow down the guessed city range.#6](https://github.com/sopra-fs23-group-32/SoPra23_Server/issues/6)
