### ISSUE TITLE
Make MyProfile Page similar to rest of App

### ISSUE THREAD

**Issue by VukadinovicJS** [sopra-fs23-group-32/SoPra23_Client#154]

**Comment by awhoa** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/a0c7ec5770fcd7e57f9b113e22bc828e7f93b4f3

**Comment by awhoa** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/a0c7ec5770fcd7e57f9b113e22bc828e7f93b4f3
