### ISSUE TITLE
Creation "Invite Game" Page/Window UI

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Client#19]
[As a logged-in user, I want to be able to choose the Multiplayers Mode and invite my friends through a link#8](https://github.com/sopra-fs23-group-32/SoPra23_Server/issues/8)

**Comment by VukadinovicJS** [comment]
1e72185d0868c3fd7fdab011a81f9c31fd68e13f

**Comment by VukadinovicJS** [comment]
1e72185d0868c3fd7fdab011a81f9c31fd68e13f
