### ISSUE TITLE
Improve Game UI

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Client#68]

**Comment by leyixu21** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/4836a2b5fd9cbb28dafd8cde61962e222ed554be

**Comment by leyixu21** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/d4ec9ddc54de3551ab4072f150380cdd6b2da236
Polish RoundCountPage for single player mode and multiplayer mode

**Comment by leyixu21** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/0839f00a41658648a6f02da0fcee4d09fa292df6
