### ISSUE TITLE
Set up the edit profile page layout

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Client#7]

**Comment by leyixu21** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/4329e4ef37fb26e7574fba21c8ba8eddd717b385
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/f533ed35a7e4420b0ec246107dd3bb0404e501d8

**Comment by leyixu21** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/0b50a71254df0d052b467f45a2fa0b4f6c32c88d
