### ISSUE TITLE
Implement Websocket in Frontend

### ISSUE THREAD

**Issue by VukadinovicJS** [sopra-fs23-group-32/SoPra23_Client#76]

**Comment by VukadinovicJS** [comment]
54bf7ff16b9187ebf07156cd54f7d15e81d11425

**Comment by dominic1712** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/81552efb1f5d2240c97692590e877205ee5e6a09#diff-c7e39d44640297bb6f84cbb9cc3797fca9991c695a04fed608fad056b9902598
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/2cf099d6dd87e8a2b0c91852dfff94a251a615a7
