### ISSUE TITLE
Make all UI pages response, scrollable (for smaller devices), Add pagination for scoreboard and game history

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Client#85]

**Comment by leyixu21** [comment]
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/32b79d22c6404789530db6f53d14d4084b7af6bb
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/dec307baa2adbc4553df326bf6a5251680a69086
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/f82fedb0045d6082e4caccb503b5eb91cba996f5
https://github.com/sopra-fs23-group-32/SoPra23_Client/commit/50705bc363b9206f03e337a41211b5a20f9c94d7
